//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use wiki_domain::response::{DeploymentStatus, GitRevision};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "deployment")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(column_type = "Text", unique_key = "single_active_deployment")]
    pub project_id: String,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub revision: Option<GitRevision>,
    pub status: DeploymentStatus,
    #[sea_orm(unique_key = "single_active_deployment")]
    pub active: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub user_id: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub source_repo: String,
    #[sea_orm(column_type = "Text")]
    pub source_branch: String,
    #[sea_orm(column_type = "Text")]
    pub source_path: String,
    pub created_at: DateTime,
    #[sea_orm(
        belongs_to,
        from = "project_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub project: HasOne<super::project::Entity>,
    #[sea_orm(has_many)]
    pub project_issues: HasMany<super::project_issue::Entity>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub user: HasOne<super::user::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
