//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "item")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub loc: String,
    #[sea_orm(has_one)]
    pub project_item: HasOne<super::project_item::Entity>,
    #[sea_orm(has_many)]
    pub recipe_ingredient_items: HasMany<super::recipe_ingredient_item::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
