//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod prelude;

pub mod access_key;
pub mod data_import;
pub mod deployment;
pub mod item;
pub mod project;
pub mod project_issue;
pub mod project_item;
pub mod project_item_page;
pub mod project_page;
pub mod project_tag;
pub mod project_version;
pub mod recipe;
pub mod recipe_ingredient_item;
pub mod recipe_ingredient_tag;
pub mod recipe_type;
pub mod recipe_workbench;
pub mod report;
pub mod tag;
pub mod tag_item;
pub mod tag_item_flat;
pub mod tag_tag;
pub mod user;
pub mod user_project;
