//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::access_key::Entity as AccessKey;
pub use super::data_import::Entity as DataImport;
pub use super::deployment::Entity as Deployment;
pub use super::item::Entity as Item;
pub use super::project::Entity as Project;
pub use super::project_issue::Entity as ProjectIssue;
pub use super::project_item::Entity as ProjectItem;
pub use super::project_item_page::Entity as ProjectItemPage;
pub use super::project_page::Entity as ProjectPage;
pub use super::project_tag::Entity as ProjectTag;
pub use super::project_version::Entity as ProjectVersion;
pub use super::recipe::Entity as Recipe;
pub use super::recipe_ingredient_item::Entity as RecipeIngredientItem;
pub use super::recipe_ingredient_tag::Entity as RecipeIngredientTag;
pub use super::recipe_type::Entity as RecipeType;
pub use super::recipe_workbench::Entity as RecipeWorkbench;
pub use super::report::Entity as Report;
pub use super::tag::Entity as Tag;
pub use super::tag_item::Entity as TagItem;
pub use super::tag_tag::Entity as TagTag;
pub use super::user::Entity as User;
pub use super::user_project::Entity as UserProject;
