//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use wiki_domain::error::{ProjectError, ProjectIssueLevel, ProjectIssueType};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "project_issue")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub level: ProjectIssueLevel,
    pub deployment_id: String,
    pub r#type: ProjectIssueType,
    pub subject: ProjectError,
    #[sea_orm(column_type = "Text", nullable)]
    pub details: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub file: Option<String>,
    pub version_name: Option<String>,
    pub created_at: DateTime,
    #[sea_orm(
        belongs_to,
        from = "deployment_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub deployment: HasOne<super::deployment::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
