//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "project_page")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub version_id: i64,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub r#ref: String,
    #[sea_orm(column_type = "Text")]
    pub path: String,
    #[sea_orm(
        belongs_to,
        from = "version_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub project_version: HasOne<super::project_version::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
