//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "project_version")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(
        column_type = "Text",
        unique_key = "project_version_project_id_name_branch_key"
    )]
    pub project_id: String,
    #[sea_orm(unique_key = "project_version_project_id_name_branch_key")]
    pub name: Option<String>,
    #[sea_orm(unique_key = "project_version_project_id_name_branch_key")]
    pub branch: String,
    #[sea_orm(
        belongs_to,
        from = "project_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub project: HasOne<super::project::Entity>,
    #[sea_orm(has_many)]
    pub project_items: HasMany<super::project_item::Entity>,
    #[sea_orm(has_many)]
    pub project_tags: HasMany<super::project_tag::Entity>,
    #[sea_orm(has_many)]
    pub recipes: HasMany<super::recipe::Entity>,
    #[sea_orm(has_many)]
    pub recipe_types: HasMany<super::recipe_type::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
