//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use wiki_domain::project::ProjectType;
use wiki_domain::visibility::ProjectVisibility;

#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize, FromJsonQueryResult)]
pub struct Platforms(pub HashMap<String, String>);

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "project")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "project_source_repo_source_path_key"
    )]
    pub source_path: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "project_source_repo_source_path_key"
    )]
    pub source_repo: String,
    #[sea_orm(column_type = "Text")]
    pub source_branch: String,
    pub is_community: bool,
    pub r#type: ProjectType,
    #[sea_orm(column_type = "JsonBinary")]
    pub platforms: Platforms,
    #[sea_orm(
        ignore,
        column_type = "custom(\"tsvector\")",
        select_as = "text",
        nullable
    )]
    pub search_vector: Option<String>,
    pub created_at: DateTime,
    pub is_public: bool,
    pub modid: Option<String>,
    pub is_virtual: bool,
    pub visibility: ProjectVisibility,
    #[sea_orm(column_type = "Text", nullable)]
    pub flags: Option<String>,
    #[sea_orm(has_many)]
    pub deployments: HasMany<super::deployment::Entity>,
    #[sea_orm(has_many)]
    pub project_versions: HasMany<super::project_version::Entity>,
    #[sea_orm(has_many, via = "user_project")]
    pub users: HasMany<super::user::Entity>,
    #[sea_orm(has_many)]
    pub user_projects: HasMany<super::user_project::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
