//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "project_item")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub item_id: i64,
    #[sea_orm(unique_key = "project_item_item_id_version_id_key")]
    pub version_id: i64,
    #[sea_orm(
        belongs_to,
        from = "item_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub item: HasOne<super::item::Entity>,
    #[sea_orm(has_many)]
    pub project_item_pages: HasMany<super::project_item_page::Entity>,
    #[sea_orm(
        belongs_to,
        from = "version_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub project_version: HasOne<super::project_version::Entity>,
    #[sea_orm(has_many, via = "tag_item")]
    pub project_tags: HasMany<super::project_tag::Entity>,
    #[sea_orm(has_many, via = "recipe_workbench")]
    pub recipe_types: HasMany<super::recipe_type::Entity>,
    #[sea_orm(has_many)]
    pub flat_tags: HasMany<super::tag_item_flat::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
