//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "project_tag")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub tag_id: i64,
    #[sea_orm(unique_key = "project_tag_tag_id_version_id_key")]
    pub version_id: i64,
    #[sea_orm(
        belongs_to,
        from = "version_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub project_version: HasOne<super::project_version::Entity>,
    #[sea_orm(
        belongs_to,
        from = "tag_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub tag: HasOne<super::tag::Entity>,
    #[sea_orm(has_many, via = "tag_item")]
    pub project_items: HasMany<super::project_item::Entity>,
    #[sea_orm(has_many)]
    pub flat_items: HasMany<super::tag_item_flat::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
