//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "recipe")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique_key = "recipe_version_id_loc_key")]
    pub version_id: i64,
    #[sea_orm(unique)]
    pub loc: String,
    pub type_id: i64,
    #[sea_orm(
        belongs_to,
        from = "version_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub project_version: HasOne<super::project_version::Entity>,
    #[sea_orm(has_many)]
    pub recipe_ingredient_items: HasMany<super::recipe_ingredient_item::Entity>,
    #[sea_orm(has_many)]
    pub recipe_ingredient_tags: HasMany<super::recipe_ingredient_tag::Entity>,
    #[sea_orm(
        belongs_to,
        from = "type_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub recipe_type: HasOne<super::recipe_type::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
