//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "recipe_type")]
pub struct Model {
    #[sea_orm(primary_key, unique_key = "recipe_type_id_version_id_key")]
    pub id: i64,
    #[sea_orm(unique)]
    pub loc: Option<String>,
    #[sea_orm(unique_key = "recipe_type_id_version_id_key")]
    pub version_id: Option<i64>,
    #[sea_orm(
        belongs_to,
        from = "version_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub project_version: HasOne<super::project_version::Entity>,
    #[sea_orm(has_many)]
    pub recipes: HasMany<super::recipe::Entity>,
    #[sea_orm(has_many, via = "recipe_workbench")]
    pub project_items: HasMany<super::project_item::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
