//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "recipe_ingredient_tag")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub recipe_id: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub tag_id: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub slot: String,
    pub count: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub input: bool,
    #[sea_orm(
        belongs_to,
        from = "recipe_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub recipe: HasOne<super::recipe::Entity>,
    #[sea_orm(
        belongs_to,
        from = "tag_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub tag: HasOne<super::tag::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
