//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use wiki_domain::visibility::{ReportReason, ReportStatus, ReportType};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "report")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub r#type: ReportType,
    #[sea_orm(column_type = "Text")]
    pub reason: ReportReason,
    #[sea_orm(column_type = "Text")]
    pub body: String,
    pub status: ReportStatus,
    #[sea_orm(column_type = "Text")]
    pub submitter_id: String,
    #[sea_orm(column_type = "Text")]
    pub project_id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub path: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub locale: Option<String>,
    pub version_id: Option<i64>, // TODO Use version_name
    pub created_at: DateTime,
}

impl ActiveModelBehavior for ActiveModel {}
