//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "tag")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub loc: Option<String>,
    #[sea_orm(has_one)]
    pub project_tag: HasOne<super::project_tag::Entity>,
    #[sea_orm(has_many)]
    pub recipe_ingredient_tags: HasMany<super::recipe_ingredient_tag::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
