//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "tag_item")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub tag_id: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub item_id: i64,
    #[sea_orm(
        belongs_to,
        from = "item_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub project_item: HasOne<super::project_item::Entity>,
    #[sea_orm(
        belongs_to,
        from = "tag_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub project_tag: HasOne<super::project_tag::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
