//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "tag_tag")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub parent: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub child: i64,
    #[sea_orm(
        belongs_to,
        relation_enum = "ProjectTag2",
        from = "child",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub project_tag_2: HasOne<super::project_tag::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "ProjectTag1",
        from = "parent",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub project_tag_1: HasOne<super::project_tag::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
