//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use wiki_domain::response::UserRole;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "user_")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub modrinth_id: Option<String>,
    pub created_at: DateTime,
    pub role: UserRole,
    #[sea_orm(has_many)]
    pub access_keys: HasMany<super::access_key::Entity>,
    #[sea_orm(has_many)]
    pub data_imports: HasMany<super::data_import::Entity>,
    #[sea_orm(has_many)]
    pub deployments: HasMany<super::deployment::Entity>,
    #[sea_orm(has_many, via = "user_project")]
    pub projects: HasMany<super::project::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
