// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AccessKeyInfo = {
  id: number;
  name: string;
  user_id: string | null;
  expires_at: string | null;
  created_at: string;
};
