// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectError } from "./ProjectError";
import type { ProjectIssueLevel } from "./ProjectIssueLevel";
import type { ProjectIssueType } from "./ProjectIssueType";

export type AddIssueRequestBody = {
  level: ProjectIssueLevel;
  type: ProjectIssueType;
  subject: ProjectError;
  details: string;
  path: string | null;
};
