// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectVisibility } from "./ProjectVisibility";

export type AdminProjectInfo = {
  id: string;
  name: string;
  type: string;
  visibility: ProjectVisibility;
  created_at: string;
};
