// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BrowseProject = {
  id: string;
  name: string;
  type: string;
  platforms: { [key in string]: string };
  is_community: boolean;
  created_at: string;
};
