// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BrowseProject } from "./BrowseProject";

export type BrowseResponse = {
  pages: number;
  total: number;
  data: Array<BrowseProject>;
};
