// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type ContentItemResponse = {
  content: string;
  edit_url: string | null;
  properties: { [key in string]: JsonValue };
};
