// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileType } from "./FileType";

export type ContentFileTreeEntry = {
  id?: string | null;
  name: string;
  icon?: string | null;
  path: string;
  type: FileType;
  children: Array<ContentFileTreeEntry>;
};
