// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccessKeyBrief } from "./AccessKeyBrief";

export type CreateAccessKeyResponse = { key: AccessKeyBrief; token: string };
