// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DataImportInfo = {
  id: number;
  game_version: string;
  loader: string;
  loader_version: string;
  user_id: string | null;
  created_at: string;
};
