// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeploymentStatus } from "./DeploymentStatus";
import type { GitRevision } from "./GitRevision";
import type { ProjectIssueInfo } from "./ProjectIssueInfo";

export type DeploymentInfo = {
  id: string;
  project_id: string;
  revision: GitRevision | null;
  status: DeploymentStatus;
  active: boolean;
  user_id: string | null;
  source_repo: string;
  source_branch: string;
  source_path: string;
  created_at: string;
  issues: Array<ProjectIssueInfo> | null;
};
