// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitRevision } from "./GitRevision";

export type DeploymentEvent =
  | { type: "created"; deployment_id: string }
  | { type: "loading"; deployment_id: string }
  | { type: "revision"; deployment_id: string; revision: GitRevision }
  | { type: "success"; deployment_id: string }
  | { type: "error"; deployment_id: string };
