// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectIssueInfo } from "./ProjectIssueInfo";
import type { JsonValue } from "./serde_json/JsonValue";

export type DeploymentInfo = {
  id: string;
  project_id: string;
  revision: JsonValue | null;
  status: string;
  active: boolean;
  user_id: string | null;
  source_repo: string;
  source_branch: string;
  source_path: string;
  created_at: string;
  issues: Array<ProjectIssueInfo> | null;
};
