// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChangelogEntry } from "./ChangelogEntry";
import type { GameContentType } from "./GameContentType";
import type { Infobox } from "./Infobox";

export type Frontmatter = {
  id: Array<string>;
  title: string | null;
  infobox: Infobox | null;
  type: GameContentType | null;
  custom: { [key in string]: string } | null;
  history: Array<ChangelogEntry> | null;
};
