// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResolvedGameRecipe } from "./ResolvedGameRecipe";

export type FullRecipeData = { id: string; data: ResolvedGameRecipe };
