// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItemSlot } from "./ItemSlot";

export type GameRecipeType = {
  id: string;
  localized_name: string | null;
  background: string;
  input_slots: { [key in string]: ItemSlot };
  output_slots: { [key in string]: ItemSlot };
};
