// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItemSlot } from "./ItemSlot";

export type GameRecipeType = {
  id: string | null;
  localizedName: string | null;
  background: string;
  inputSlots: { [key in string]: ItemSlot };
  outputSlots: { [key in string]: ItemSlot };
};
