// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GitRevision = {
  hash: string;
  fullHash: string;
  message: string;
  authorName: string;
  authorEmail: string;
  date: string;
  url: string | null;
};
