// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GitRevision = {
  hash: string;
  full_hash: string;
  message: string;
  author_name: string;
  author_email: string;
  date: string;
  url: string | null;
};
