// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InfoboxTab } from "./InfoboxTab";

export type Infobox = {
  title: string | null;
  tabs?: Array<InfoboxTab> | null;
  inventory: Array<string>;
};
