// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InfoboxTab = {
  name: string;
  /**
   * Must be list of valid ResourceLocations
   */
  display: Array<string>;
};
