// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PaginatedData<T> = {
  total: number;
  pages: number;
  size: number;
  data: Array<T>;
};
