// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectMember } from "./ProjectMember";

export type ProjectMembersData = {
  members: Array<ProjectMember>;
  can_edit: boolean;
  can_leave: boolean;
};
