// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Licenses } from "./Licenses";
import type { ProjectSchemaVersion } from "./ProjectSchemaVersion";

export type ProjectMetadata = {
  schema: ProjectSchemaVersion;
  id: string;
  modid?: string | null;
  platforms?: { [key in string]: string } | null;
  versions?: { [key in string]: string } | null;
  platform?: string | null;
  slug?: string | null;
  owners?: Array<string> | null;
  licenses?: Licenses | null;
};
