// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitRevision } from "./GitRevision";
import type { ProjectFlag } from "./ProjectFlag";
import type { ProjectIssueLevel } from "./ProjectIssueLevel";
import type { ProjectMemberRole } from "./ProjectMemberRole";
import type { ProjectStatus } from "./ProjectStatus";
import type { ProjectType } from "./ProjectType";
import type { ProjectVisibility } from "./ProjectVisibility";

export type ProjectDetails = {
  id: string;
  name: string;
  type: ProjectType;
  platforms: { [key in string]: string };
  is_community: boolean;
  created_at: string;
  source_repo: string;
  source_branch: string;
  source_path: string;
  visibility: ProjectVisibility;
  is_public: boolean;
  flags: Array<ProjectFlag>;
  status: ProjectStatus;
  has_active_deployment: boolean;
  access_level: ProjectMemberRole;
  revision: GitRevision | null;
  issue_stats: { [key in ProjectIssueLevel]?: number };
  has_failing_deployment: boolean;
};
