// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectFlag } from "./ProjectFlag";
import type { ProjectMemberRole } from "./ProjectMemberRole";
import type { ProjectStatus } from "./ProjectStatus";
import type { ProjectVisibility } from "./ProjectVisibility";

export type ProjectDetails = {
  id: string;
  name: string;
  type: string;
  platforms: Array<string>;
  is_community: boolean;
  created_at: string;
  source_repo: string;
  source_branch: string;
  source_path: string;
  visibility: ProjectVisibility;
  is_public: boolean;
  flags: Array<ProjectFlag> | null;
  status: ProjectStatus | null;
  has_active_deployment: boolean | null;
  access_level: ProjectMemberRole | null;
};
