// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectError } from "./ProjectError";
import type { ProjectIssueLevel } from "./ProjectIssueLevel";
import type { ProjectIssueType } from "./ProjectIssueType";

export type ProjectIssueInfo = {
  id: string;
  level: ProjectIssueLevel;
  deployment_id: string;
  type: ProjectIssueType;
  subject: ProjectError;
  details: string | null;
  file: string | null;
  version_name: string | null;
  created_at: string;
};
