// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectInfo } from "./ProjectInfo";
import type { ProjectType } from "./ProjectType";

export type ProjectInfoResponse = {
  id: string;
  name: string;
  type: ProjectType;
  platforms: { [key in string]: string };
  is_community: boolean;
  created_at: string;
  source_repo: string | null;
  versions: Array<string>;
  locales: Array<string>;
  local: boolean;
  info: ProjectInfo;
};
