// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectLicenses } from "./ProjectLicenses";

export type ProjectInfo = {
  page_count: number;
  content_count: number;
  licenses: ProjectLicenses;
};
