// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Frontmatter } from "./Frontmatter";
import type { JsonValue } from "./serde_json/JsonValue";

export type ProjectPage = {
  frontmatter: Frontmatter;
  content: string;
  edit_url: string | null;
  properties: { [key in string]: { [key in string]: JsonValue } };
};
