// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProjectError =
  | "ok"
  | "requires_auth"
  | "no_repository"
  | "repo_too_large"
  | "no_branch"
  | "no_path"
  | "invalid_meta"
  | "page_render"
  | "duplicate_page"
  | "unknown_recipe_type"
  | "invalid_ingredient"
  | "invalid_file"
  | "invalid_format"
  | "invalid_resloc"
  | "invalid_version_branch"
  | "invalid_frontmatter"
  | "missing_platform_project"
  | "no_page_title"
  | "missing_required_attribute"
  | "unknown";
