// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectType } from "./ProjectType";

export type ProjectSummary = {
  id: string;
  name: string;
  type: ProjectType;
  platforms: { [key in string]: string };
  is_community: boolean;
  source_repo: string | null;
  created_at: string;
};
