// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DevProjectData } from "./DevProjectData";

export type ProjectCreatedResponse = {
  project: DevProjectData;
  message: string;
};
