// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileTreeEntry } from "./FileTreeEntry";

export type ProjectInfoResponse = {
  id: string;
  versions: { [key in string]: string };
  tree: Array<FileTreeEntry>;
};
