// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProjectIssueType =
  | "meta"
  | "file"
  | "git_clone"
  | "git_info"
  | "ingestor"
  | "version_setup"
  | "internal";
