// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProjectIssueInfo = {
  id: string;
  level: string;
  deployment_id: string;
  type: string;
  subject: string;
  details: string | null;
  file: string | null;
  version_name: string | null;
  created_at: string;
};
