// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameRecipeType } from "./GameRecipeType";
import type { ResolvedItem } from "./ResolvedItem";

export type RecipeTypeResponse = {
  type: GameRecipeType;
  workbenches: Array<ResolvedItem>;
};
