// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecipeIngredientSummary } from "./RecipeIngredientSummary";

export type RecipeSummary = {
  inputs: Array<RecipeIngredientSummary>;
  outputs: Array<RecipeIngredientSummary>;
};
