// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResolvedItem } from "./ResolvedItem";

export type RecipeIngredientSummary = {
  count: number;
  item: ResolvedItem;
  tag: string | null;
};
