// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReportReason } from "./ReportReason";
import type { ReportStatus } from "./ReportStatus";
import type { ReportType } from "./ReportType";

export type ReportInfo = {
  id: string;
  type: ReportType;
  reason: ReportReason;
  body: string;
  status: ReportStatus;
  submitter_id: string;
  project_id: string;
  path: string | null;
  locale: string | null;
  version: string | null;
  created_at: string;
};
