// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReportStatus } from "./ReportStatus";

export type ReportInfo = {
  id: string;
  type: string;
  reason: string;
  body: string;
  status: ReportStatus;
  submitter_id: string;
  project_id: string;
  path: string | null;
  locale: string | null;
  version_id: number | null;
  created_at: string;
};
