// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResolvedLinkType } from "./ResolvedLinkType";

export type ResolvedLink = {
  type: ResolvedLinkType;
  ref: string;
  title?: string | null;
};
