// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResolvedItem } from "./ResolvedItem";

export type ResolvedSlot = {
  input: boolean;
  slot: string;
  count: number;
  items: Array<ResolvedItem>;
  tag: string | null;
};
