// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecipeSummary } from "./RecipeSummary";
import type { ResolvedSlot } from "./ResolvedSlot";

export type ResolvedGameRecipe = {
  id: string;
  type: string;
  inputs: Array<ResolvedSlot>;
  outputs: Array<ResolvedSlot>;
  summary: RecipeSummary;
};
