// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ResolvedItem = {
  id: string;
  name: string | null;
  project: string | null;
  has_page: boolean;
};
