// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DataImportInfo } from "./DataImportInfo";
import type { SystemStats } from "./SystemStats";

export type SystemInfoResponse = {
  version: string;
  latest_data: DataImportInfo | null;
  stats: SystemStats;
};
