// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileTreeEntry } from "./FileTreeEntry";

export type TreeResponse = { tree: Array<FileTreeEntry> };
