// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DevProjectData } from "./DevProjectData";
import type { UserProfile } from "./UserProfile";

export type UserProjectsResponse = {
  profile: UserProfile;
  projects: Array<DevProjectData>;
};
