// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserProfile = {
  username: string;
  name: string;
  role: string;
  modrinth_id: string | null;
  avatar_url: string | null;
  created_at: string;
};
